# Generated by Django 5.2.3 on 2025-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('packaging_material', models.CharField(max_length=120)),
                ('shelf_life_days', models.PositiveBigIntegerField()),
                ('transport_distance_km', models.FloatField()),
                ('transport_mode', models.CharField(max_length=15)),
                ('supplier_certifications', models.JSONField(blank=True, default=list)),
                ('origin_country', models.CharField(max_length=60)),
                ('total_score', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
